# Generated by Django 4.0.5 on 2022-07-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='user/profile/default.png', upload_to='user/profile/pictures', verbose_name='nuotrauka'),
        ),
    ]
